site_name: 2020_5DI_Team4
nav:
    - 'Project Charter': 'project_charter.md'
    - 'Software Requirements Specification': 'software_requirements_specification.md'
    - 'Software Project Management Plan': 'software_projeckt_management_plan.md'
    - 'Business Model Canvas': 'business_model_canvas.pdf'
    - 'Project Model Canvas': 'project_model_canvas.pdf'
    - 'Release Plan': 'release_plan.md'
    - 'Iteration Plan': 'iteration_plan.md'
    - 'Memo of Understanding': 'memo_of_understanding.md' 
    - 'Project Success Criteria': 'project_success_criteria.md'
    - 'Architecture and Design': 'architecture_and_design.md'  
    - 'Test Plan': 'test_plan.md'
    - 'Test Case Specification ': 'test_case_specification.md'
    - 'User Guide': 'user_guide.md'
    - 'System Documentation': 'system_documentation.md' 
    - 'GDPR DPA': 'gdpr_dpa.md'
    
    - 'Project Charter PDF': 'project_charter.pdf'
    - 'Software Requirements Specification PDF': 'software_requirements_specification.pdf'
    - 'Software Project Management Plan PDF': 'software_projeckt_management_plan.pdf'
    - 'Release Plan PDF': 'release_plan.pdf'
    - 'Iteration Plan PDF': 'iteration_plan.pdf'
    - 'Memo of Understanding PDF': 'memo_of_understanding.pdf' 
    - 'Project Success Criteria PDF': 'project_success_criteria.pdf'
    - 'Architecture and Design PDF': 'architecture_and_design.pdf'  
    - 'Test Plan PDF': 'test_plan.pdf'
    - 'Test Case Specification PDF': 'test_case_specification.pdf'
    - 'User Guide PDF': 'user_guide.pdf'
    - 'System Documentation PDF': 'system_documentation.pdf'
    - 'GDPR DPA PDF': 'gdpr_dpa.pdf'
   
    
theme:
    name: readthedocs

use_directory_urls: true
